CREATE TYPE "public"."job_type" AS ENUM('all', 'full-time', 'part-time', 'contract', 'intern');--> statement-breakpoint
CREATE TYPE "public"."location" AS ENUM('전체', '서울', '경기', '인천', '강원', '충청', '전라', '경상', '제주');--> statement-breakpoint
CREATE TYPE "public"."salary_range" AS ENUM('전체', '5000만원 이상', '4000만원 ~ 5000만원', '3000만원 ~ 4000만원', '2000만원 ~ 3000만원', '1000만원 ~ 2000만원', '1000만원 이하');--> statement-breakpoint
CREATE TABLE "jobs" (
	"job_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "jobs_job_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"position" text NOT NULL,
	"overview" text NOT NULL,
	"responsibilities" text NOT NULL,
	"qualifications" text NOT NULL,
	"benefits" text NOT NULL,
	"company_id" bigint NOT NULL,
	"company_name" text NOT NULL,
	"company_logo" text NOT NULL,
	"company_location" text NOT NULL,
	"apply_url" text NOT NULL,
	"job_type" "job_type" NOT NULL,
	"location" "location" NOT NULL,
	"salary_range" "salary_range" NOT NULL
);
